### ISSUE TITLE
Questions to understand code

### ISSUE THREAD

**Issue by JigaoLuo** [kawasin73/umutex#1]
Hi. I have following questions to understand your code:

- Should `success` also be protected by a mutex? Is this variable thread safe? Should it be thread safe?https://github.com/kawasin73/umutex/blob/ec50c08927a0dded5250dff8116dbba3d8c19487/umutex.go#L44
- The same question to variable `u`.

**Comment by kawasin73** [comment]
Hi @cakebytheoceanLuo . sorry for my late reply.

`success` is a local variable, so it is obviously thread safe.

We need to think about that the operations on `m.u` is thread safe or not here.

If you handle `m.u` like following, it is not thread safe. It may happen a data race on incrementing `m.u` and there is no guarantee that the value of `m.u` in `m.u == 1` is same with the incrementing result.

```go
m.u += 1
success := m.u == 1
```

`atomic` package will solve this thread safe problem. `atomic` package use atomic instructions of CPU and avoid the data race.
https://golang.org/pkg/sync/atomic/

I use `atomic.AddInt32(&m.u, 1)` from `atomic` package. Even when some threads execute this function exactly same time on each CPU core, CPU will coordinate and serialize each atomic instruction executions then the function returns different results for each threads (only 1 thread receives `1` result and others receive more).

`atomic.AddInt32(&m.u, 1)` has a same functionality like following.

```go
// shared mutex
var mu sync.Mutex

func addInt32() int32 {
  mu.Lock()
  m.u += 1
  v := m.u
  mu.Unlock()
  return v
}
```

You may also wonder why i use `atomic` function instead of mutex. It is because mutex is slow and complex. a `atomic` instruction is only 1 CPU instruction, but mutex is more as you can see and the `Lock` `Unlock` functionalities are also complecated.

---

Have you seen a implementation of `sync.Mutex` ? ( https://golang.org/src/sync/mutex.go )

```go
// Lock locks m.
// If the lock is already in use, the calling goroutine
// blocks until the mutex is available.
func (m *Mutex) Lock() {
	// Fast path: grab unlocked mutex.
	if atomic.CompareAndSwapInt32(&m.state, 0, mutexLocked) {
		if race.Enabled {
			race.Acquire(unsafe.Pointer(m))
		}
		return
	}
	// Slow path (outlined so that the fast path can be inlined)
	m.lockSlow()
}
```

It uses `atomic.CompareAndSwapInt32` function in `atomic` package for fast aquireing a lock ( It is called "Spin Lock" ). It is not the same function i used, but the concept about data race is similar.

It will help you to understand about mutex to see this youtube video [Let's Talk Locks! - YouTube](https://www.youtube.com/watch?v=7OpCf6f_BAM) which is a tech talk about Go's lock.
